### ISSUE TITLE
Improve CSS for the print media type

### ISSUE THREAD

**Issue by dhedlund** [activate/ActivateHub#28]
Design some CSS overrides to hide the navigation/chrome of the website when printing a page.  This is really important for when someone wants to print out the description of an event and the accompanying map.

Unlike the mobile views, and due to how few overrides will be needed, it probably makes the most sense to embed `@media ...` definitions with the CSS properties themselves.  80% or more of the overrides will probably be in the `app/assets/stylesheets/print.scss` file and can be written like:

``` scss
#navbar {
  position: fixed;
  ...

  @media print {
    display: none;
  }
}
```
